/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:e8559eeb-484e-41c1-8afc-051f4ec28e5d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_wTNLSi4IE",
    "aws_user_pools_web_client_id": "5lttjurc82bfqldj477k5b24t",
    "oauth": {}
};


export default awsmobile;
